autoware_new_planning_launch/package.xml
The autoware_prefix is missing for glog_component.
The error occurring is ``autoware_new_planning_launch: Cannot locate rosdep definition for [glog_component]` `.
This PR, adds autoware prefix.
=> fix(new_planning_launch): fix package.xml

autoware_trajectory_adaptor/src/node.cpp, autoware_trajectory_selector_common/src/evaluation.cpp
Currently, the normalize function does not normalize each metric when there is a single candidate path.
This PR fixes the issue.
Furthermore the logging level is changed to `DEBUG`, in order to keep the terminal clean.
(The metrics or score is trying to be visualized by lichtblick)
=> fix(common): normalize metrics when candidate path size is 1

autoware_trajectory_metrics/src/metrics.cpp, autoware_trajectory_ranker/src/node.cpp, autoware_trajectory_selector_common/include/autoware/trajectory_selector_common/interface/metrics_interface.hpp, autoware_trajectory_selector_common/src/evaluation.cpp
Sampling number and time resolution used for trajectory evaluation was hard coded.
This has been fixed in this PR.
=> fix(ranker, metrics): use parameter instead of hard code

autoware_new_planning_framework/package.xml, autoware_new_planning_launch/launch/selector.launch.xml, autoware_new_planning_launch/package.xml, autoware_trajectory_concatenater/README.md, autoware_trajectory_concatenator/CMakeLists.txt, autoware_trajectory_concatenator/README.md, autoware_trajectory_concatenator/package.xml, autoware_trajectory_concatenator/src/node.cpp, autoware_trajectory_concatenator/src/node.hpp
Fix spelling from concatenater to concatenator. 
(There seems to be vocab "concatenator", although it suggests spelling mistakes in certain dictionaries.
May be should change to trajectory_concatenate, but this would be out of subject right now.
=> fix(concatenator): spelling

autoware_new_planning_msgs/CMakeLists.txt, autoware_new_planning_msgs/msg/TrajectoryPoint.msg
There TrajectoryPoint.msg is not used currently as it uses [autoware_planning_msgs/TrajectoryPoint](https://github.com/autowarefoundation/autoware_msgs/blob/main/autoware_planning_msgs/msg/TrajectoryPoint.msg). 
Since it is unnecessary it would be removed.
=> refactor(msgs): delete TrajectoryPoint.msg

autoware_trajectory_ranker/src/node.cpp, autoware_trajectory_ranker/src/node.hpp, autoware_trajectory_selector_common/include/autoware/trajectory_selector_common/evaluation.hpp, autoware_trajectory_selector_common/src/evaluation.cpp
Added a publisher that publishes the scoring debug message of the selected trajectory.
| Change type   | Topic Type      | Topic Name    | Message Type        | Description       |
|:--------------|:----------------|:--------------|:--------------------|:------------------|
| Added | Pub | `/trajectory_ranker/output/score_debug` | `autoware_new_planning_msgs/msg/ScoreDebug`   | best trajectory score information for debug |
Checked by the command below:
`$ ros2 topic echo /trajectory_ranker/output/score_debug`
The output on terminal is
```
generator_info:
generator_id:
uuid:
- 37
- 105
- 186
- 130
- 81
- 85
- 5
- 118
- 248
- 128
- 0
- 45
- 138
- 88
- 13
- 73
generator_name:
data: __anon
score: 1.7000000476837158
metrics:
- LateralAcceleration
- LongitudinalJerk
- TravelDistance
- …
```
=> feat(trajectory_ranker)!: publish best score trajectory

autoware_trajectory_ranker/src/node.cpp, autoware_trajectory_ranker/src/node.hpp, autoware_trajectory_selector_common/include/autoware/trajectory_selector_common/evaluation.hpp, autoware_trajectory_selector_common/src/evaluation.cpp
With this PR all trajectories scoring information is published by using the message format introduced in https://github.com/tier4/new_planning_framework/pull/54.
| Change type   | Topic Type      | Topic Name    | Message Type        | Description       |
|:--------------|:----------------|:--------------|:--------------------|:------------------|
| Modified | Pub | `/trajectory_ranker/output/score_debug` | `autoware_new_planning_msgs/msg/TrajectoriesDebug`   | score information for each trajectory |
Launched 2 planning components and checked that the debug message was published.
The raw message was successfully subscribed in lichtblick.
=> feat(trajectory_ranker)!: publish debug info for multiple trajectories

autoware_trajectory_selector_common/src/evaluation.cpp
With the current implementation, `best()` might return a `nullptr` which leads to memory access error when getting header information from `best()->header()`.
This PR fixes the issue, by using the clock time and hard coding the `frame_id`.
=> fix(trajectory_selector_common): assign variable directly to msg header

autoware_trajectory_adaptor/package.xml, autoware_trajectory_adaptor/src/node.cpp
Current Autoware controller cannot handle trajectory with duplicated point inside.
This PR removes duplicated points before publishing the selected trajectory.
=> feat(trajectory_adaptor): remove duplicated point

autoware_trajectory_selector_common/src/utils.cpp
Wrong type was passed to the argument in previous PR https://github.com/tier4/new_planning_framework/pull/63.
Fixed in this PR
=> fix(trajectory_selector_common): argument bug

autoware_new_planning_launch/launch/selector.launch.xml, autoware_offline_evaluation_tools/src/evaluation.cpp, autoware_offline_evaluation_tools/src/evaluation.hpp, autoware_trajectory_metrics/src/metrics.cpp, autoware_trajectory_ranker/src/node.cpp, autoware_trajectory_ranker/src/node.hpp, autoware_trajectory_selector_common/include/autoware/trajectory_selector_common/interface/data_interface.hpp, autoware_trajectory_selector_common/include/autoware/trajectory_selector_common/structs.hpp
Use current steering information instead of calculating the steering angle from `utils::steer_command`.
=> feat: add current steering information

autoware_trajectory_selector_common/include/autoware/trajectory_selector_common/utils.hpp, autoware_trajectory_selector_common/src/utils.cpp
Ego segment index was used to resample the trajectories point. This PR changes to obtaining the nearest index instead, enabling to cope with trajectories that are behind the ego vehicle.
=> fix(trajectory_selector_common): change method to get nearest index

autoware_feasible_trajectory_filter/param/parameter_struct.yaml, autoware_feasible_trajectory_filter/src/node.cpp
This PR excludes trajectories that has less than 2 points.
Also the out of lane condition is checked with a time range.
=> feat(feasible_trajectory_filter): exclude invalid trajectory

autoware_trajectory_metrics/src/metrics.cpp, autoware_trajectory_metrics/src/utils.cpp
The trajectory generator should store the following information at least:
- time_from_start
- pose
- velocity (both longitudinal and lateral)
Therefore the metrics used in the selector should be recalculated from the above information.
=> fix(trajectory_metrics): update each metrics

autoware_new_planning_launch/launch/selector.launch.xml, autoware_trajectory_adaptor/src/node.cpp, autoware_trajectory_adaptor/src/node.hpp
Add hazard signal information for temporary usage.
This should be take into account with the turn indicator, whether it would be coped inside the trajectory adapter.
=> feat(trajectory_adapter): add hazard signal information

autoware_new_planning_launch/launch/generator.launch.xml
Delete redundant config file descriptions
=> fix the generator launch to allow launching the trajectory interpolator

autoware_new_planning_launch/launch/selector.launch.xml, autoware_trajectory_concatenator/CMakeLists.txt, autoware_trajectory_concatenator/config/concatenator.param.yaml, autoware_trajectory_concatenator/package.xml, autoware_trajectory_concatenator/param/parameter_struct.yaml, autoware_trajectory_concatenator/src/node.cpp, autoware_trajectory_concatenator/src/node.hpp, autoware_trajectory_concatenator/src/structs.hpp, autoware_trajectory_selector_common/include/autoware/trajectory_selector_common/utils.hpp, autoware_trajectory_selector_common/src/utils.cpp
Add a feedback loop for the selected trajectory.
The loop can be turned on/off by parameters.
It might be better to implement this function in another node, and would need further consideration.
Checked that the concatenated trajectory size is 7(6 output from MTR and 1 from the selected trajectory)
=> feat(trajectory_concatenator) :concatenate selected trajectory

autoware_trajectory_metrics/src/utils.cpp
If the shared_ptr `objects` was nullptr, the process will die.
This would be resolved by this PR.
=> fix(trajectory_metrics): argument check

autoware_feasible_trajectory_filter/src/node.cpp, autoware_feasible_trajectory_filter/src/node.hpp, autoware_offline_evaluation_tools/src/evaluation.cpp, autoware_trajectory_ranker/src/node.cpp, autoware_trajectory_ranker/src/node.hpp, autoware_trajectory_selector_common/include/autoware/trajectory_selector_common/interface/data_interface.hpp, autoware_trajectory_selector_common/include/autoware/trajectory_selector_common/structs.hpp
Eliminate trajectories whose origin is a certain distance away from the ego vehicle's position.
Was able to drive in PSim
=> feat(feasible_trajectory_filter): check path origin

autoware_feasible_trajectory_filter/package.xml, autoware_feasible_trajectory_filter/src/node.cpp, autoware_feasible_trajectory_filter/src/node.hpp, autoware_new_planning_launch/launch/selector.launch.xml
Check for trajectory start position was introduced in PR: https://github.com/tier4/new_planning_framework/pull/90.
This would be suitable to a lot of E2E model based generator.
However some generators would generate trajectories with some margin behind the ego vehicle. (ex. Autoware behavior path planner)
Thus, the nearest point to the ego vehicle is checked instead. If the nearest point is certain distance away from the ego vehicle the candidate trajectory is eliminated.
Moved the ego vehicle suddenly in PSim and checked that the output becomes 0, even though there are multiple candidates as inputs.
[Screencast from 2025年04月01日 16時39分51秒.webm](https://github.com/user-attachments/assets/acd11f91-bea2-4209-af14-6dc3ee3a69a0)
=> feat(feasible_trajectory_filter): check path off tracking instead of only checking the origin

autoware_trajectory_metrics/src/metrics.cpp, autoware_trajectory_selector_common/include/autoware/trajectory_selector_common/evaluation.hpp, autoware_trajectory_selector_common/src/evaluation.cpp
Change normalization method.
- Before multiplying the `time_decay_weight`, each metric value is normalized. The denominator for normalization is defined as a parameter
- Before multiplying the `score_weight`, each metric sum is normalized. The denominator for normalization is defined as the sum of the `time_decay_weight`
=> feat(trajectory_metrics, selector_common): modify normalize method

autoware_new_planning_msgs_converter/package.xml, autoware_new_planning_msgs_converter/src/trajectory_to_trajectories.hpp
Due to changes in autoware, the dependency name for uuid utilities is different
=> fix dependency issue for uuid

autoware_valid_trajectory_filter/package.xml, autoware_valid_trajectory_filter/src/node.cpp, autoware_valid_trajectory_filter/src/node.hpp
Before (odaiba map): 
ros2 topic echo /valid_trajectory_filter/debug/processing_time_detail_ms
nodes:
- id: 1
name: process
processing_time: 216.058
parent_id: 0
comment: ''
- id: 2
name: traffic_light_check
processing_time: 216.036
parent_id: 1
comment: ''
---
nodes:
- id: 1
name: process
processing_time: 236.775
parent_id: 0
comment: ''
- id: 2
name: traffic_light_check
processing_time: 236.752
parent_id: 1
comment: ''
After: 
nodes:
- id: 1
name: process
processing_time: 0.143
parent_id: 0
comment: ''
- id: 2
name: traffic_light_check
processing_time: 0.133
parent_id: 1
comment: ''
- id: 3
name: get_lanelets_from_trajectory
processing_time: 0.126
parent_id: 2
comment: ''
- id: 4
name: get_lanelets_from_trajectory
processing_time: 0.126
parent_id: 3
comment: ''
- id: 5
name: …
=> use boundary departure checker to speed up lanelet queries
